server:
    port: 8084

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/redis_test?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: bao026099
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 2000
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
      database: 0
      timeout: 3000ms
#        哨兵模式配置
#      sentinel:
#        master:
#        nodes:
      jedis:
        pool:
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
          max-active: 8
          time-between-eviction-runs: 3000ms
      cluster:
        nodes:
          - 10.3.0.79:7001
          - 10.3.0.79:7002
          - 10.3.0.79:7003
          - 10.3.0.79:7004
          - 10.3.0.79:7005
          - 10.3.0.79:7006
          - 10.3.0.82:7001
          - 10.3.0.82:7002
          - 10.3.0.82:7003
          - 10.3.0.82:7004
          - 10.3.0.82:7005
          - 10.3.0.82:7006
          - 10.3.0.83:7001
          - 10.3.0.83:7002
          - 10.3.0.83:7003
          - 10.3.0.83:7004
          - 10.3.0.83:7005
          - 10.3.0.83:7006
          - 10.3.0.84:7001
          - 10.3.0.84:7002
          - 10.3.0.84:7003
          - 10.3.0.84:7004
          - 10.3.0.84:7005
          - 10.3.0.84:7006
mybatis:
  type-aliases-package: com.byr.demo.mapper
  mapper-locations:  classpath:mapper/*.xml





